server:
  port: 7003
  servlet:
    context-path: /user
spring:
  application:
    name: user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/user-center?useUnicode=true&zeroDateTimeBehavior=CONVERT_TO_NULL&characterEncoding=utf8
    username: root
    password: 3306
  redis:
    host: 110.41.135.108
    port: 37690
    timeout: 5000
eureka:
  instance:
    hostname: 110.41.135.108/eruka
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}/eureka/
feign:
  hystrix:
    enabled: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true  #开启驼峰功能
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.user.domain.*  # 注意：对应实体类的路径
initialization:
   userName: admin
   password: admin
   customPwd: 8888888
